FROM docker.io/python:3.8-buster
LABEL maintainer="Andrew Simonson <asimonson1125@gmail.com>"

WORKDIR /server
COPY ./server .
RUN apt-get -yq update && \
    pip install --no-cache-dir -r requirements.txt

CMD [ "gunicorn", "app:app" ]