FROM docker.io/python:3.8-buster
LABEL maintainer="Andrew Simonson <asimonson1125@gmail.com>"

WORKDIR /collector
COPY ./collector .
RUN apt-get -yq update && \
    pip3 install --no-cache-dir -r requirements.txt


CMD [ "python3", "scheduler.py" ]